version: '3.9'

networks:
  backend:
  frontend:
services:
  db:
    image: postgres:latest
    container_name: db
    volumes:
      - /products:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      HOST: ${HOST}
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - backend
  django:
    image: my_dj_docker
    build: .
    container_name: django_gunicorn
    depends_on:
      - db
    volumes:
      - /djangologs:/usr/src/app
      - data-static:/Worktask/app/static
    env_file:
      - .env
    environment:
      POSTGRES_HOST: ${HOST}
    networks:
      - backend
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn --workers 4 --bind 0.0.0.0:8000 productlist.wsgi:application"
  nginx:
    build: 
      dockerfile: ./Dockerfile
      context: ./nginx-conf.d/nginx/
    container_name: djnginx
    image: dj-nginx
    ports:
      - "80:80"
    networks: 
      - backend
      - frontend
    volumes:
      - ./nginx-conf.d/nginx:/etc/nginx/conf.d
      - data-static:/Worktask/app/static
    depends_on:
      - django

volumes:
  products:
  djangologs:
  data-static:
