# Generated by Django 5.0.1 on 2024-01-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('category', models.CharField(choices=[('овощи', 'Vegetables'), ('фрукты', 'Fruits'), ('мясо', 'Meat'), ('напитки', 'Drinks'), ('другое', 'Others')], max_length=7)),
            ],
        ),
    ]
