name: Тестирование и развертывание проекта

on:
  push:
    branches:
      - new_branch

jobs:
  tests:
    runs-on: ubuntu-22.04
    env:
      SECRET_VALUE: ${{ secrets.SECRET }}
      DEBUG_MODE: "0"
      ALLOWED: ${{ secrets.ALLOWED_HOSTS }}
      ENGINE: ${{ secrets.DB_ENGINE }}
      USER: ${{ secrets.DB_USER }}
      PASSWORD: ${{ secrets.DB_PASSWORD }}
      NAME: ${{ secrets.DB_NAME }}
      HOST: ${{ secrets.DB_HOST }}
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: ${{ env.NAME }}
          POSTGRES_USER: ${{ env.USER }}
          POSTGRES_PASSWORD: ${{ env.PASSWORD }}
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Проверяем репозиторий на наличие изменений
        uses: actions/checkout@v4

      - name: Установка python и окружения
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Установка библиотек
        run: pip install -r requirements.txt

      - name: Линтинг
        run: flake8 app/ --exclude=app/migrations/

      - name: Тестирование
        run: python manage.py test
        env:
          SECRET_KEY: ${{ env.SECRET }}
          DEBUG: ${{ env.DEBUG }}
          ALLOWED_HOSTS: ${{ env.ALLOWED_HOSTS }}
          DB_ENGINE: ${{ env.DB_ENGINE }}
          DB_NAME: ${{ env.DB_NAME }}
          DB_USER: ${{ env.DB_USER }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
          DB_HOST: ${{ env.DB_HOST }}
          DB_PORT: ${{ env.DB_PORT }}


